---
name: assignment-1-career-narrative
break: true
indent: 4
---

writing/narrative.md:
    ConfirmFileExists
    proselint
    CountFileParagraphs --count 4
    CountMarkdownTags --tag "heading" --count 4
    MatchFileFragment --fragment "TODO" --count 0 --exact
