name: GatorGrader

on:
  push:
    branches: [ main ]

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
    - uses: gabrielfalcao/pyenv-action@v6
      with:
        default: 3.6.3
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Set up grading environment
      run: |
        pyenv global 3.6.3
        export PATH="/home/runner/.local/bin:$PATH"
        pip install --upgrade pip
        pip install proselint
        pip install pipenv
        pipenv install --dev --three
    - name: Grade assignment
      run: |
        gradle grade
      if: always()
