name: GatorGrader

on:
  push:
    branches: [ main ]

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Set up grading environment
      run: |
        export PATH="/home/runner/.local/bin:$PATH"
        pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --three
    - name: Grade assignment
      run: |
        gradle grade
      if: always()
